# Generated by Django 5.1.2 on 2024-10-22 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 22, 12, 12, 43, 11856, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
